// npm install @mui/material @emotion/react @emotion/styled
// npm install @mui/material-nextjs @emotion/cache
// npm install stylis stylis-plugin-rtl
// npm i --save-dev @types/stylis
// npm install zustand for global state managment

import { Box, Toolbar } from "@mui/material";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Header from "./Header";
import MuiCustomThemeProvider from "./MuiCustomeThemeProvider";
import { MuiRtlAndAppRouterCacheProvider } from "./MuiRtl&Cache";
import SideBar from "./SideBar";
import "./globals.css";

// this is the way of importing a local font
const IranSansWeb = localFont({
  src: "../public/fonts/teqh_iransansweb.ttf",
  variable: "--font-IranSansWeb",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl">
      <body className={IranSansWeb.variable}>
        {/* this is for custom mui theme */}
        <MuiCustomThemeProvider>
          {/* this is for mui-rtl and catch-provider */}
          <MuiRtlAndAppRouterCacheProvider>
            <Box sx={{ display: "flex" }}>
              <SideBar />
              <Header />
              <Box
                component="main"
                sx={{
                  flexGrow: 1,
                  p: 1,
                  width: { sm: `calc(100% - ${240}px)` },
                }}
              >
                <Toolbar />
                {children}
              </Box>
            </Box>
          </MuiRtlAndAppRouterCacheProvider>
        </MuiCustomThemeProvider>
      </body>
    </html>
  );
}
