// npm install @mui/material @emotion/react @emotion/styled
// npm install @mui/material-nextjs @emotion/cache
// npm install stylis stylis-plugin-rtl
// npm i --save-dev @types/stylis
// npm install zustand for global state managment
// npx -y next-video init
// npm install axios
// npm i @tanstack/react-query
// npm i @tanstack/react-query-devtools
import { Box, Toolbar } from "@mui/material";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Header from "./Header";
import MuiCustomThemeProvider from "./MuiCustomeThemeProvider";
import { MuiRtlAndAppRouterCacheProvider } from "./MuiRtl&Cache";
import SideBar from "./SideBar";
import "./globals.css";
import ReactQueryProvider from "./QueryClientProvider";
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
// this is the way of importing a local font
const IranSansWeb = localFont({
  src: "../public/fonts/teqh_iransansweb.ttf",
  variable: "--font-IranSansWeb",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl">
      <body className={IranSansWeb.variable}>
        {/* this is for custom mui theme */}
        <MuiCustomThemeProvider>
          {/* this is for mui-rtl and catch-provider */}
          <MuiRtlAndAppRouterCacheProvider>
            <ReactQueryProvider>
              <Box sx={{ display: "flex" }}>
                <SideBar />
                <Header />
                <Box
                  component="main"
                  sx={{
                    flexGrow: 1,
                    width: { md: `calc(100% - ${240}px)` },
                  }}
                >
                  <Toolbar />
                  <main className="bg-[#1E2027] p- h-[91.33vh]">
                    {children}
                  </main>
                </Box>
              </Box>
              <ReactQueryDevtools initialIsOpen={false} />
            </ReactQueryProvider>
          </MuiRtlAndAppRouterCacheProvider>
        </MuiCustomThemeProvider>
      </body>
    </html>
  );
}
